---
title: "R 控制语句"
output: html_notebook
---



```{r}
1==1
#> [1] TRUE
1!=1
#> [1] FALSE
1<2
#> [1] TRUE
x<-1
if (x==1)
{
print("hello")
}
#> [1] "hello"
y<-function(x)
{
if (x==1)
{
print("hello")
}else
{
print("goodbye")
}
}
```
控制语句下的多种情况 else if
```{r}
z<-function(x)
{
if(x==1)
{ print("hello")
}else if(x==0)
{
print("goodbye")
}else
{
print("confused")
}
}
z(1)
```
switch语句
```{r}
use.switch<-function(x)
{
switch(x,"a"="first","b"="second","z"="last","c"="third","others")
}
use.switch("a")
#> [1] "first"
use.switch(2)#如果第一个参数是数字，不管接下来的参数是什么名字，它跟在后面的参数是定位匹配，如果这个数值参数大于后续参数的数量，则返回NULL#
#> [1] "second"
```
ifelse语句
第一个参数是被检查的条件，第三第二个参数是检查的条件为真时的返回值，个参数是检查的条
件为时的返回值，和if语句不同在于可用于向量化参数
```{r}
ifelse(1==1,"yes","no")
#> [1] "yes"
c<-c(1,0,0,1,0,1)
ifelse(c==1,"yes","no")
ifelse(c==1,c*3,c)
ifelse(c==1,c*3,c)
```
复合检查
&，&&，|，||,单重形式用于ifelse，双重形式最好用if，双重形式仅仅比较两边的一个元素，单重
形式比较两边的每一个。
```{r}
a<-c(1,1,0,1)
b<-c(2,1,0,1)
ifelse(a==1&b==1,"yes","no")
#> [1] "no" "yes" "no" "yes"
ifelse(a==1&&b==1,"yes","no")
```
循环，Un-R方式的迭代
```{r}
for (i in 1:10)
{
print(i)
}
fruit<-c("apple","banana","pomegranate")
length(fruit)
#> [1] 3
fruitlength<-rep(NA,length(fruit))
fruitlength
#> [1] NA NA NA
names(fruitlength)<-fruitlength
for(a in fruit)
{
fruitlength[a]<-nchar(a)
}
fruitlength
fruitlength2<-nchar(fruit)
names(fruitlength2)<-fruit
fruitlength2
#> apple banana pomegranate
#> 5 6 11
identical(fruitlength,fruitlength2)
```

while循环

```{r}
x<1#会一直跑下去
while(x<=5)
{
print(x)
x<x+1
}
```


控制循环
```{r}
for(i in 1:10)
{
if(i==3)
{
next
}
print(i)
}
for(i in 1:10)
{
if(i==4)
{
break()
}
print(i)
}
```


